### PR TITLE
Fix buffer index error

### LINKED ISSUE #4: Disconnecting and reconnecting results in `undefined` being sent from `MessageBuffer`
I don't recall how the exact math works out, but this value [`i % this.messageMax`](https://github.com/zenmoto/bunyan-tcp/blob/master/index.js#L39) is not guaranteed to be less than `oldBuffer.length` which results in `undefined` applied to `cb`. This only pops up if you connect, send logs, disconnect, reconnect, and attempts to `drain` the `MessageBuffer`.

Using `Array.shift`/`Array.push` instead of comparing `mod`s of counts and lengths resolves this.

### PR DESCRIPTION
**Pull request by amsross**
resolves #4 

The index for `oldBuffer` isn't guaranteed to be valid/correct. Rather than figure out why, just skip all that math and use some `Array` methods.

Also add a test to expose the issue.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -33,14 +31,9 @@ MessageBuffer.prototype.drain = function(cb) {
...
-    var startIdx = this.messagesAdded % oldBuffer.length;
-    for (var i=startIdx; i<(oldBuffer.length + startIdx); i++) {
-      cb(oldBuffer[i % this.messageMax]);
-    }
-  } else {
-    oldBuffer.forEach(cb);
-  }
+  oldBuffer.forEach(cb);
+
+  this.messagesAdded = 0;
```
Comment (amsross) [inline index.js:36]: After looking at this some more, this may have been the only required change. I would say the whole index thing is a little simpler now, but that's pretty subjective.
